apiVersion: v1
kind: Service
metadata:
  name: cv-inference
  namespace: mlops-cv
  labels:
    app: cv-inference
spec:
  selector:
    app: cv-inference
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
