apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cv-inference
  namespace: mlops-cv
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: cv-inference
  namespaceSelector:
    matchNames:
      - mlops-cv
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
